### ISSUE TITLE
Doc

### ISSUE THREAD

**Issue by migmake** [boboldehampsink/onedashboard#1]
Sorry I cannot understand how to make it work.
More info in README please ?
Thanks.

**Comment by boboldehampsink** [comment]
`This plugin will install the admin's widgets for every new CP user, so you can have more control over the default user widgets.`

This is what the README says. In other words: when you have widgets (as admin), and you create a new user with this plugin enabled, the new user will get the same widgets as you have. Is this clear?

**Comment by migmake** [comment]
Yes that I can understand. But my widgets were already enabled for my new users before I installed your plugin. So I was expectings some more advanced feature. I cannot see whats new with this plugin. Perhaps it was useful with previous versions of CRAFT ?

**Comment by boboldehampsink** [comment]
Craft's default behavior is that every new user gets all widgets. My plugin makes it so that you get to pick what widgets a new user gets.

**Comment by migmake** [comment]
Hmm ok. But I have mutliple groups of users. It will not be sufficient in my case. I was more searching for a clear vision and control of wich widgets are enabled and assigned to user groups. I would have like to see a new tab in user groups for example.

**Comment by boboldehampsink** [comment]
That would be awesome, but unfortunately this is not supported by Craft as of yet. You might want to vote on this: http://feedback.buildwithcraft.com/forums/285221-feature-requests/suggestions/8665627-add-or-remove-dashboard-items-per-user-group

**Comment by migmake** [comment]
OK done ! :) Thanks.
